<?php
/**
 * Created by PhpStorm.
 * User: nmoller
 * Date: 03/12/17
 * Time: 2:09 PM
 */

namespace Tests\Feature;

use App\Billing\PaymentGateway;
use App\Concert;
use App\Billing\FakePaymentGateway;
use Carbon\Carbon;
use Tests\TestCase;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Foundation\Testing\WithoutMiddleware;

class PurchaseTicketTest extends TestCase
{
    use DatabaseMigrations;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->paymentGateway = new FakePaymentGateway();
        $this->app->instance(PaymentGateway::class, $this->paymentGateway);
    }

    /**
     * @test
     */
    function customer_can_purchase_concert_tickets()
    {
        $concert = factory(Concert::class)->create([
                'ticket_price' => 3250
        ]);


        $response = $this->json('POST', "/concerts/{$concert->id}/orders", [
            'email' => 'john@example.com',
            'ticket_quantity' => 3,
            'payment_token' => $this->paymentGateway->getValidTestToken(),
        ]);

        $response->assertStatus(201);

        $this->assertEquals(9750, $this->paymentGateway->totalCharges());

        $order = $concert->orders()->where('email', 'john@example.com')->first();
        $this->assertNotNull($order);
        $this->assertEquals(3, $order->tickets->count());
    }

    /**
     * @test
     */
    function email_is_required_to_purchase_tickets()
    {
        //$this->withoutExceptionHandling();

        $concert = factory(Concert::class)->create();

        $response = $this->json('POST', "/concerts/{$concert->id}/orders", [
            'ticket_quantity' => 3,
            'payment_token' => $this->paymentGateway->getValidTestToken(),
        ]);

        $response->assertStatus(422);
        $jsonRet = $response->decodeResponseJson();
        $this->assertArrayHasKey('email', $jsonRet['errors']);
        // To learn about the structure of the response
        //dd($response->decodeResponseJson());
    }
}