<?php
/**
 * Created by PhpStorm.
 * User: nmoller
 * Date: 03/12/17
 * Time: 2:09 PM
 */

namespace Tests\Feature;

use App\Billing\PaymentGateway;
use App\Concert;
use App\Billing\FakePaymentGateway;
use Carbon\Carbon;
use Tests\TestCase;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Foundation\Testing\WithoutMiddleware;

class PurchaseTicketTest extends TestCase
{
    use DatabaseMigrations;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->paymentGateway = new FakePaymentGateway();
        $this->app->instance(PaymentGateway::class, $this->paymentGateway);
    }

    private function orderTickets($concert, $params)
    {
         return $this->json('POST', "/concerts/{$concert->id}/orders", $params);
    }

    private function assertValidationError($response, $field)
    {
        $response->assertStatus(422);
        $jsonRet = $response->decodeResponseJson();
        $this->assertArrayHasKey($field, $jsonRet['errors']);
    }

    /**
     * @test
     */
    function customer_can_purchase_concert_tickets()
    {
        $concert = factory(Concert::class)->create([
                'ticket_price' => 3250
        ]);


        $response = $this->orderTickets($concert, [
            'email' => 'john@example.com',
            'ticket_quantity' => 3,
            'payment_token' => $this->paymentGateway->getValidTestToken(),
        ]);

        $response->assertStatus(201);

        $this->assertEquals(9750, $this->paymentGateway->totalCharges());

        $order = $concert->orders()->where('email', 'john@example.com')->first();
        $this->assertNotNull($order);
        $this->assertEquals(3, $order->tickets->count());
    }

    /**
     * @test
     */
    function email_is_required_to_purchase_tickets()
    {
        //$this->withoutExceptionHandling();

        $concert = factory(Concert::class)->create();

        $response = $this->orderTickets($concert, [
            'ticket_quantity' => 3,
            'payment_token' => $this->paymentGateway->getValidTestToken(),
        ]);

        $this->assertValidationError($response, 'email');

        // To learn about the structure of the response
        //dd($response->decodeResponseJson());
    }

    /**
     * @test
     */
    function email_must_be_valid_to_purchase_tickets()
    {
        //$this->withoutExceptionHandling();

        $concert = factory(Concert::class)->create();

        $response = $this->orderTickets($concert, [
            'email' => 'an-invalid-email',
            'ticket_quantity' => 3,
            'payment_token' => $this->paymentGateway->getValidTestToken(),
        ]);

        $this->assertValidationError($response, 'email');
        // To learn about the structure of the response
        //dd($response->decodeResponseJson());
    }

    /**
     * @test
     */
    function ticket_quantity_is_required_to_purchase_tickets()
    {
        //$this->withoutExceptionHandling();

        $concert = factory(Concert::class)->create();

        $response = $this->orderTickets($concert, [
            'email' => 'john@example.com',
            'payment_token' => $this->paymentGateway->getValidTestToken(),
        ]);

        $this->assertValidationError($response, 'ticket_quantity');
        // To learn about the structure of the response
        //dd($response->decodeResponseJson());
    }

    /**
     * @test
     */
    function ticket_quantity_must_be_at_least_1_to_purchase_tickets()
    {
        //$this->withoutExceptionHandling();

        $concert = factory(Concert::class)->create();

        $response = $this->orderTickets($concert, [
            'email' => 'john@example.com',
            'ticket_quantity' => 0,
            'payment_token' => $this->paymentGateway->getValidTestToken(),
        ]);

        $this->assertValidationError($response, 'ticket_quantity');
        // To learn about the structure of the response
        //dd($response->decodeResponseJson());
    }

    /**
     * @test
     */
    function payment_token_is_required()
    {
        //$this->withoutExceptionHandling();

        $concert = factory(Concert::class)->create();

        $response = $this->orderTickets($concert, [
            'email' => 'john@example.com',
            'ticket_quantity' => 3,
        ]);

        $response->assertStatus(422);
        $jsonRet = $response->decodeResponseJson();
        $this->assertArrayHasKey('payment_token', $jsonRet['errors']);
        // To learn about the structure of the response
        //dd($response->decodeResponseJson());
    }

    /**
     * @test
     */
    function an_order_is_not_created_if_payment_fails() {
        $concert = factory(Concert::class)->create(['ticket_price' => 3250]);

        $response = $this->orderTickets($concert, [
            'email' => 'john@example.com',
            'ticket_quantity' => 0,
            'payment_token' => 'invalid-payment-token',
        ]);

        $response->assertStatus(422);
        $order = $concert->orders()->where('email', 'john@example.com')->first();
        $this->assertNull($order);
    }
}